const BOOKS = [
  {
    title: "日本写真史（上）",
    subtitle: "幕末維新から高度成長期まで",
    author: "鳥原学",
    year: 2013,
    origYear: null,
    publisher: "中央公論新社",
    amazon: "https://amzn.asia/d/0gB8ZizV",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "日本写真史（下）",
    subtitle: "安定成長期から3・11後まで",
    author: "鳥原学",
    year: 2013,
    origYear: null,
    publisher: "中央公論新社",
    amazon: "https://amzn.asia/d/0bDtpS3J",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "西洋音楽史",
    subtitle: "「クラシック」の黄昏",
    author: "岡田暁生",
    year: 2005,
    origYear: null,
    publisher: "中央公論新社",
    amazon: "https://amzn.asia/d/0bDtpS3J",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "現代音楽史",
    subtitle: "闘争しつづける芸術のゆくえ",
    author: "沼野雄司",
    year: 2021,
    origYear: null,
    publisher: "中央公論新社",
    amazon: "https://amzn.asia/d/0ehLtLd2",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "現代美術史",
    subtitle: "欧米、日本、トランスナショナル",
    author: "山本浩貴",
    year: 2019,
    origYear: null,
    publisher: "中央公論新社",
    amazon: "https://amzn.asia/d/09YGm8kZ",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "現代思想入門",
    subtitle: "",
    author: "千葉雅也",
    year: 2022,
    origYear: null,
    publisher: "講談社",
    amazon: "https://amzn.asia/d/06bvA7fe",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "インスタグラムと視覚文化論",
    subtitle: "レフ・マノヴィッチのカルチュラル・アナリティクスをめぐって",
    author: "レフ・マノヴィッチ，久保田晃弘，きりとりめでる（編訳）ほか",
    year: 2018,
    origYear: 2017,
    publisher: "ビー・エヌ・エヌ新社",
    amazon: "https://amzn.asia/d/0eZTkz6O",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "フィールド・レコーディング入門",
    subtitle: "響きのなかで世界と出会う",
    author: "柳沢英輔",
    year: 2022,
    origYear: null,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/00Kk20SX",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "明るい部屋",
    subtitle: "写真についての覚書",
    author: "ロラン・バルト，花輪光（訳）",
    year: 1997,
    origYear: 1980,
    publisher: "みすず書房",
    amazon: "https://amzn.asia/d/0aTKSOSn",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "音響メディア史",
    subtitle: "",
    author: "谷口文和，中川克志，福間裕大",
    year: 2015,
    origYear: null,
    publisher: "ナカニシヤ出版",
    amazon: "https://amzn.asia/d/0cENey1k",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "現象学入門",
    subtitle: "",
    author: "竹田青嗣",
    year: 1989,
    origYear: null,
    publisher: "NHK出版",
    amazon: "https://amzn.asia/d/08JlFQBS",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "アフターミュージッキング",
    subtitle: "実践する音楽",
    author: "毛利嘉孝（監）ほか",
    year: 2017,
    origYear: null,
    publisher: "東京藝術大学出版会",
    amazon: "https://amzn.asia/d/03viugBX",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "クリティカル・ワード\n メディア論",
    subtitle: "",
    author: "門林岳史，増田展大（編著）",
    year: 2021,
    origYear: null,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/0dx1GfWS",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "超解読！はじめてのカント\n『純粋理性批判』",
    subtitle: "",
    author: "竹田青嗣",
    year: 2011,
    origYear: null,
    publisher: "講談社現代新書",
    amazon: "https://amzn.asia/d/0hrZkNrE",
    description: "ドイツの哲学者イマヌエル・カントによる『純粋理性批判』（1787年）の入門書である。筆者によれば、「哲学の予備知識があまりない一般の読者でも、それなりに『純粋理性批判』の独自のストーリーを追えるように配慮」した一冊である（p.313）。本書では、『純粋理性批判』を「認識はどのようにして成り立つのか」という問題として読み解き、反哲学の時代という現代的な状況も踏まえながら、想定される批判や筆者独自の解釈を交えて、その思想の展開を解説している。",
    impressions: [
      {
        date: "26.7.12",
        text: `カントのことは少しだけ知っている。以前、<a href="https://www.youtube.com/@yurutetsugaku" target="_blank" rel="noopener noreferrer">ゆる哲学ラジオ</a>で見た。感性、悟性、理性。純粋悟性概念、アプリオリな綜合判断など。言葉自体は聞いたことがある。

今回は、先験的分析論、つまり「純粋悟性概念（＝私たちが経験を対象として理解するために、悟性がもともと備えているカテゴリー）は、なぜ経験に適用できるのか」という議論まで読み進めた。『純粋理性批判』のストーリーはざっくりと、Ⅰ「人間はどのように認識できるのか」を明らかにし、Ⅱ「その認識能力をどのように正しく用いるべきか」を論じる本であるように思う。カントは人間理性（観念）を、感性、悟性、理性の三つに分けて考える。今回読んだ範囲では、感性、悟性とは何か、そして悟性は感性によって与えられたものをどのように判断するのか、というところまで理解した。つまり、Ⅰの途中までということになる。細かな内容についてはここには書かない。

きちんと難解な本である。初学者にとって難しい言葉がたくさん出てくるので、根気もいるだろう。ただ、忘れてはいけないのは、私は「カントは何が言いたいのか」を知りたいということだ。本書を、本書のまま理解しなくていい。本書がカントの考えを理解する一助になればいい。実際に読むかはさておき、原著『純粋理性批判』に備えて、知識を武装することが重要だ。

先日、私の通う大学院の研究員の方とお話しする機会があった。私の作品についてや、聴取の哲学に関心を持っていることを話したところ、「私の作品は『時間感覚の再考』という観点で捉えることもできるかもね」、という話になった。また、哲学では空間や時間は重要なテーマであり、メルロ＝ポンティは空間、ベルクソンは時間だという話も聞いた。（それ故に、林林書林には『ベルクソン入門』が入荷されている。）だからこそ、本書で「空間と時間はアプリオリ（≒先験的）な感性の形式であり、対象が空間や時間の中に現れるのではなく、私たちが空間・時間という形式によって対象を受け取る」という議論は、私にとってタイムリーな話だった。感性については、時間の哲学の系譜の中でベルクソンを位置づけたり、その独自性を考えたりするためにも、再読したい。

悟性については、まだ十分に理解できたとは言えない。それでも、大まかなストーリーは見えてきた。まあ、気長にやっていこう。`
      }
    ],
    status: "reading",
    log: [
      { date: "26.7.12", page: "1－104, 313－318" },
    ]
  },
  {
    title: "ベルクソン入門",
    subtitle: "",
    author: "村山達也",
    year: 2025,
    origYear: null,
    publisher: "青土社",
    amazon: "https://amzn.asia/d/01Xclzfq",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "知覚の現象学",
    subtitle: "",
    author: "モーリス・メルロ＝ポンティ，中島盛夫（訳）",
    year: 2015,
    origYear: 1945,
    publisher: "法政大学出版局",
    amazon: "https://amzn.asia/d/03wcj5YV",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "眼がスクリーンになるとき",
    subtitle: "ゼロから読むドゥルーズ『シネマ』",
    author: "福尾匠",
    year: 2024,
    origYear: null,
    publisher: "河出文庫",
    amazon: "https://amzn.asia/d/0adeQ19J",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "技術哲学入門",
    subtitle: "ポスト現象学とテクノサイエンス",
    author: "ドン・アイディ，稲垣諭ほか（訳）",
    year: 2025,
    origYear: 2009,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/0dddbR1g",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "小さなデザインの哲学",
    subtitle: "",
    author: "ヴィレム・フルッサー，瀧本雅志（訳）",
    year: 2009,
    origYear: 1993,
    publisher: "鹿島出版会",
    amazon: "https://amzn.asia/d/0abOtDzd",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "写真の哲学のために",
    subtitle: "",
    author: "ヴィレム・フルッサー，深川雅文（訳）",
    year: 1999,
    origYear: 1983,
    publisher: "勁草書房",
    amazon: "https://amzn.asia/d/022sq9zg",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "写真論",
    subtitle: "",
    author: "スーザン・ソンタグ，近藤耕人（訳）",
    year: 2026,
    origYear: 1977,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/01IcZIJW",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "写真のアルケオロジー",
    subtitle: "",
    author: "ジェフリー・バッチェン，前川修ほか（訳）",
    year: 2010,
    origYear: 1997,
    publisher: "青弓社",
    amazon: "https://amzn.asia/d/03mdo5wJ",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "世界の調律",
    subtitle: "サウンドスケープとはなにか",
    author: "レイモンド・マリー・シェーファー，鳥越けい子ほか（訳）",
    year: 2006,
    origYear: 1977,
    publisher: "平凡社",
    amazon: "https://amzn.asia/d/04EYqQGn",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "聞こえくる過去",
    subtitle: "音響再生産の文化的起源",
    author: "ジョナサン・スターン，中川克志ほか（訳）",
    year: 2015,
    origYear: 2003,
    publisher: "インスクリプト",
    amazon: "https://amzn.asia/d/0gvYJNd6",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "パフォーマンス・アート",
    subtitle: "未来派から現代まで",
    author: "ローズリー・ゴールドバーグ，深川雅文（監訳）",
    year: 2026,
    origYear: 1979,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/0gaeeibO",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "実験音楽",
    subtitle: "ケージとその後",
    author: "マイケル・ナイマン，椎名亮輔（訳）",
    year: 1992,
    origYear: 1974,
    publisher: "水声社",
    amazon: "https://amzn.asia/d/0f5kI2Ow",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "実験音楽",
    subtitle: "1970年から現代まで",
    author: "ジェニ・ゴチョーク，杉本拓ほか（訳）",
    year: 2026,
    origYear: 2016,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/0aMglDff",
    description: "",
    impression: "",
    status: "unread"
  },

  {
    title: "現代世界における日常生活",
    subtitle: "",
    author: "アンリ・ルフェーブル，森本和夫（訳）",
    year: 2026,
    origYear: 1968,
    publisher: "筑摩書房",
    amazon: "https://amzn.asia/d/04Wzct3e",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "複製技術時代の芸術",
    subtitle: "",
    author: "ヴァルター・ベンヤミン，佐々木基一（訳）",
    year: 1999,
    origYear: 1936,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/01jiAVet",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "現代写真論",
    subtitle: "コンテンポラリーアートとしての写真のゆくえ",
    author: "シャーロット・コットン，大橋悦子ほか（訳）",
    year: 2010,
    origYear: 2004,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/00v675zC",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "観察者の系譜",
    subtitle: "",
    author: "ジョナサン・クレーリー，遠藤知巳（訳）",
    year: 2005,
    origYear: 1990,
    publisher: "以文社",
    amazon: "https://amzn.asia/d/07SOjuEk",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "WAYS OF BEING",
    subtitle: "人間以外の知性",
    author: "ジェームズ・ブライドル，岩崎晋也（訳）",
    year: 2024,
    origYear: 2022,
    publisher: "早川書房",
    amazon: "https://amzn.asia/d/019Fbei0",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "Vtuber学",
    subtitle: "",
    author: "岡本健，山野弘樹，吉川慧",
    year: 2024,
    origYear: null,
    publisher: "岩波新書",
    amazon: "https://amzn.asia/d/0e0M9LFO",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "現象学は〈思考の原理〉である",
    subtitle: "",
    author: "竹田青嗣",
    year: 2004,
    origYear: null,
    publisher: "筑摩書房",
    amazon: "https://amzn.asia/d/052RpUVV",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "キュレーションの時代",
    subtitle: "「つながり」の情報革命がはじまる",
    author: "佐々木俊尚",
    year: 2011,
    origYear: null,
    publisher: "筑摩書房",
    amazon: "https://amzn.asia/d/0d9cY2Sa",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "現象学",
    subtitle: "",
    author: "木田元",
    year: 1970,
    origYear: null,
    publisher: "岩波書店",
    amazon: "https://amzn.asia/d/00b30kHV",
    description: "",
    impression: "",
    status: "unread"
  }
];
