const BOOKS = [
  {
    title: "フィールド・レコーディング入門",
    subtitle: "響きのなかで世界と出会う",
    author: "柳沢英輔",
    year: 2022,
    origYear: null,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/00Kk20SX",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "明るい部屋",
    subtitle: "写真についての覚書",
    author: "ロラン・バルト，花輪光（訳）",
    year: 1997,
    origYear: 1980,
    publisher: "みすず書房",
    amazon: "https://amzn.asia/d/0aTKSOSn",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "音響メディア史",
    subtitle: "",
    author: "谷口文和，中川克志，福間裕大",
    year: 2015,
    origYear: null,
    publisher: "ナカニシヤ出版",
    amazon: "https://amzn.asia/d/0cENey1k",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "現象学入門",
    subtitle: "",
    author: "竹田青嗣",
    year: 1989,
    origYear: null,
    publisher: "NHK出版",
    amazon: "https://amzn.asia/d/08JlFQBS",
    description: "",
    impression: "",
    status: "read"
  },
  {
    title: "アフターミュージッキング",
    subtitle: "実践する音楽",
    author: "毛利嘉孝（監）",
    year: 2017,
    origYear: null,
    publisher: "東京藝術大学出版会",
    amazon: "https://amzn.asia/d/03viugBX",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "クリティカル・ワード　メディア論",
    subtitle: "",
    author: "門林岳史，増田展大（編著）",
    year: 2021,
    origYear: null,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/0dx1GfWS",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "超解読！はじめてのカント『純粋理性批判』",
    subtitle: "",
    author: "竹田青嗣",
    year: 2011,
    origYear: null,
    publisher: "講談社現代新書",
    amazon: "https://amzn.asia/d/0hrZkNrE",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "ベルクソン入門",
    subtitle: "",
    author: "村山達也",
    year: 2025,
    origYear: null,
    publisher: "青土社",
    amazon: "https://amzn.asia/d/01Xclzfq",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "知覚の現象学",
    subtitle: "",
    author: "モーリス・メルロ＝ポンティ，中島盛夫（訳）",
    year: 2015,
    origYear: 1945,
    publisher: "法政大学出版局",
    amazon: "https://amzn.asia/d/03wcj5YV",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "眼がスクリーンになるとき",
    subtitle: "ゼロから読むドゥルーズ『シネマ』",
    author: "福尾匠",
    year: 2024,
    origYear: null,
    publisher: "河出文庫",
    amazon: "https://amzn.asia/d/0adeQ19J",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "技術哲学入門",
    subtitle: "ポスト現象学とテクノサイエンス",
    author: "ドン・アイディ，稲垣諭ほか（訳）",
    year: 2025,
    origYear: 2009,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/0dddbR1g",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "小さなデザインの哲学",
    subtitle: "",
    author: "ヴィレム・フルッサー，瀧本雅志（訳）",
    year: 2009,
    origYear: 1993,
    publisher: "鹿島出版会",
    amazon: "https://amzn.asia/d/0abOtDzd",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "写真の哲学のために",
    subtitle: "",
    author: "ヴィレム・フルッサー，深川雅文（訳）",
    year: 1999,
    origYear: 1983,
    publisher: "勁草書房",
    amazon: "https://amzn.asia/d/022sq9zg",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "写真論",
    subtitle: "",
    author: "スーザン・ソンタグ，近藤耕人（訳）",
    year: 2026,
    origYear: 1977,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/01IcZIJW",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "写真のアルケオロジー",
    subtitle: "",
    author: "ジェフリー・バッチェン，前川修ほか（訳）",
    year: 2010,
    origYear: 1997,
    publisher: "青弓社",
    amazon: "https://amzn.asia/d/03mdo5wJ",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "世界の調律",
    subtitle: "サウンドスケープとはなにか",
    author: "レイモンド・マリー・シェーファー，鳥越けい子ほか（訳）",
    year: 2006,
    origYear: 1977,
    publisher: "平凡社",
    amazon: "https://amzn.asia/d/04EYqQGn",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "聞こえくる過去",
    subtitle: "音響再生産の文化的起源",
    author: "ジョナサン・スターン，中川克志ほか（訳）",
    year: 2015,
    origYear: 2003,
    publisher: "インスクリプト",
    amazon: "https://amzn.asia/d/0gvYJNd6",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "パフォーマンス・アート",
    subtitle: "未来派から現代まで",
    author: "ローズリー・ゴールドバーグ，深川雅文（監訳）",
    year: 2026,
    origYear: 1979,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/0gaeeibO",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "実験音楽",
    subtitle: "1970年から現代まで",
    author: "ジェニ・ゴチョーク，杉本拓ほか（訳）",
    year: 2026,
    origYear: 2016,
    publisher: "フィルムアート社",
    amazon: "https://amzn.asia/d/0aMglDff",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "現代世界における日常生活",
    subtitle: "",
    author: "アンリ・ルフェーブル，森本和夫（訳）",
    year: 2026,
    origYear: 1968,
    publisher: "筑摩書房",
    amazon: "https://amzn.asia/d/04Wzct3e",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "複製技術時代の芸術",
    subtitle: "",
    author: "ヴァルター・ベンヤミン，佐々木基一（訳）",
    year: 1999,
    origYear: 1936,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/01jiAVet",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "現代写真論",
    subtitle: "コンテンポラリーアートとしての写真のゆくえ",
    author: "シャーロット・コットン，大橋悦子ほか（訳）",
    year: 2010,
    origYear: 2004,
    publisher: "晶文社",
    amazon: "https://amzn.asia/d/00v675zC",
    description: "",
    impression: "",
    status: "reading"
  },
  {
    title: "観察者の系譜",
    subtitle: "",
    author: "ジョナサン・クレーリー，遠藤知巳（訳）",
    year: 2005,
    origYear: 1990,
    publisher: "以文社",
    amazon: "hhttps://amzn.asia/d/07SOjuEk",
    description: "",
    impression: "",
    status: "unread"
  },
  {
    title: "WAYS OF BEING",
    subtitle: "人間以外の知性",
    author: "ジェームズ・ブライドル，岩崎晋也（訳）",
    year: 2024,
    origYear: 2022,
    publisher: "早川書房",
    amazon: "https://amzn.asia/d/019Fbei0",
    description: "",
    impression: "",
    status: "unread"
  }
];
